// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddGuestToProjectArgs {
    pub project_id: __sdk::Uuid,
    pub guest_id: __sdk::Identity,
}

impl From<AddGuestToProjectArgs> for super::Reducer {
    fn from(args: AddGuestToProjectArgs) -> Self {
        Self::AddGuestToProject {
            project_id: args.project_id,
            guest_id: args.guest_id,
        }
    }
}

impl __sdk::InModule for AddGuestToProjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_guest_to_project`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_guest_to_project {
    /// Request that the remote module invoke the reducer `add_guest_to_project` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_guest_to_project:add_guest_to_project_then`] to run a callback after the reducer completes.
    fn add_guest_to_project(
        &self,
        project_id: __sdk::Uuid,
        guest_id: __sdk::Identity,
    ) -> __sdk::Result<()> {
        self.add_guest_to_project_then(project_id, guest_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_guest_to_project` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_guest_to_project_then(
        &self,
        project_id: __sdk::Uuid,
        guest_id: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_guest_to_project for super::RemoteReducers {
    fn add_guest_to_project_then(
        &self,
        project_id: __sdk::Uuid,
        guest_id: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddGuestToProjectArgs {
                project_id,
                guest_id,
            },
            callback,
        )
    }
}
