// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::file_kind_type::FileKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddFileToProjectArgs {
    pub id: __sdk::Uuid,
    pub project_id: __sdk::Uuid,
    pub path: String,
    pub kind: FileKind,
    pub parent_id: Option<__sdk::Uuid>,
}

impl From<AddFileToProjectArgs> for super::Reducer {
    fn from(args: AddFileToProjectArgs) -> Self {
        Self::AddFileToProject {
            id: args.id,
            project_id: args.project_id,
            path: args.path,
            kind: args.kind,
            parent_id: args.parent_id,
        }
    }
}

impl __sdk::InModule for AddFileToProjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_file_to_project`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_file_to_project {
    /// Request that the remote module invoke the reducer `add_file_to_project` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_file_to_project:add_file_to_project_then`] to run a callback after the reducer completes.
    fn add_file_to_project(
        &self,
        id: __sdk::Uuid,
        project_id: __sdk::Uuid,
        path: String,
        kind: FileKind,
        parent_id: Option<__sdk::Uuid>,
    ) -> __sdk::Result<()> {
        self.add_file_to_project_then(id, project_id, path, kind, parent_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_file_to_project` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_file_to_project_then(
        &self,
        id: __sdk::Uuid,
        project_id: __sdk::Uuid,
        path: String,
        kind: FileKind,
        parent_id: Option<__sdk::Uuid>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_file_to_project for super::RemoteReducers {
    fn add_file_to_project_then(
        &self,
        id: __sdk::Uuid,
        project_id: __sdk::Uuid,
        path: String,
        kind: FileKind,
        parent_id: Option<__sdk::Uuid>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddFileToProjectArgs {
                id,
                project_id,
                path,
                kind,
                parent_id,
            },
            callback,
        )
    }
}
