// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::file_kind_type::FileKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct File {
    pub id: __sdk::Uuid,
    pub path: String,
    pub kind: FileKind,
    pub parent_id: __sdk::Uuid,
    pub project_id: __sdk::Uuid,
}

impl __sdk::InModule for File {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `File`.
///
/// Provides typed access to columns for query building.
pub struct FileCols {
    pub id: __sdk::__query_builder::Col<File, __sdk::Uuid>,
    pub path: __sdk::__query_builder::Col<File, String>,
    pub kind: __sdk::__query_builder::Col<File, FileKind>,
    pub parent_id: __sdk::__query_builder::Col<File, __sdk::Uuid>,
    pub project_id: __sdk::__query_builder::Col<File, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasCols for File {
    type Cols = FileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FileCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            path: __sdk::__query_builder::Col::new(table_name, "path"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            parent_id: __sdk::__query_builder::Col::new(table_name, "parent_id"),
            project_id: __sdk::__query_builder::Col::new(table_name, "project_id"),
        }
    }
}

/// Indexed column accessor struct for the table `File`.
///
/// Provides typed access to indexed columns for query building.
pub struct FileIxCols {
    pub id: __sdk::__query_builder::IxCol<File, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for File {
    type IxCols = FileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FileIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for File {}
