// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Project {
    pub id: __sdk::Uuid,
    pub name: String,
    pub author: __sdk::Identity,
    pub guests: Vec<__sdk::Identity>,
}

impl __sdk::InModule for Project {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Project`.
///
/// Provides typed access to columns for query building.
pub struct ProjectCols {
    pub id: __sdk::__query_builder::Col<Project, __sdk::Uuid>,
    pub name: __sdk::__query_builder::Col<Project, String>,
    pub author: __sdk::__query_builder::Col<Project, __sdk::Identity>,
    pub guests: __sdk::__query_builder::Col<Project, Vec<__sdk::Identity>>,
}

impl __sdk::__query_builder::HasCols for Project {
    type Cols = ProjectCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            author: __sdk::__query_builder::Col::new(table_name, "author"),
            guests: __sdk::__query_builder::Col::new(table_name, "guests"),
        }
    }
}

/// Indexed column accessor struct for the table `Project`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectIxCols {
    pub author: __sdk::__query_builder::IxCol<Project, __sdk::Identity>,
    pub id: __sdk::__query_builder::IxCol<Project, __sdk::Uuid>,
}

impl __sdk::__query_builder::HasIxCols for Project {
    type IxCols = ProjectIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectIxCols {
            author: __sdk::__query_builder::IxCol::new(table_name, "author"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Project {}
