// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateFileContentsArgs {
    pub id: __sdk::Uuid,
    pub hash: u32,
    pub data: Vec<u8>,
}

impl From<UpdateFileContentsArgs> for super::Reducer {
    fn from(args: UpdateFileContentsArgs) -> Self {
        Self::UpdateFileContents {
            id: args.id,
            hash: args.hash,
            data: args.data,
        }
    }
}

impl __sdk::InModule for UpdateFileContentsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_file_contents`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_file_contents {
    /// Request that the remote module invoke the reducer `update_file_contents` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_file_contents:update_file_contents_then`] to run a callback after the reducer completes.
    fn update_file_contents(&self, id: __sdk::Uuid, hash: u32, data: Vec<u8>) -> __sdk::Result<()> {
        self.update_file_contents_then(id, hash, data, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_file_contents` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_file_contents_then(
        &self,
        id: __sdk::Uuid,
        hash: u32,
        data: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_file_contents for super::RemoteReducers {
    fn update_file_contents_then(
        &self,
        id: __sdk::Uuid,
        hash: u32,
        data: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateFileContentsArgs { id, hash, data }, callback)
    }
}
